export const personalInfo = {
  name: "Sathish Kumar",
  role: "Software Engineer",
  tagline: "Crafting exceptional digital experiences with code",
  bio: "Passionate software engineer with 1+ year of experience building scalable web applications. I specialize in modern JavaScript frameworks and love turning complex problems into elegant solutions.",
  email: "sathish@example.com",
  github: "https://github.com/sathish",
  linkedin: "https://linkedin.com/in/sathish",
  twitter: "https://twitter.com/sathish",
  resumeUrl: "/resume.pdf",
};

export const skills = [
  { name: "React", category: "Frontend", color: "#61DAFB" },
  { name: "Next.js", category: "Frontend", color: "#000000" },
  { name: "Angular", category: "Frontend", color: "#DD0031" },
  { name: "Tailwind CSS", category: "Frontend", color: "#06B6D4" },
  { name: "TypeScript", category: "Language", color: "#3178C6" },
  { name: "Python", category: "Language", color: "#3776AB" },
  { name: "Node.js", category: "Backend", color: "#339933" },
  { name: "GraphQL", category: "Backend", color: "#E10098" },
  { name: "PostgreSQL", category: "Database", color: "#4169E1" },
  { name: "MongoDB", category: "Database", color: "#47A248" },
  { name: "AWS", category: "Cloud", color: "#FF9900" },
  { name: "Docker", category: "DevOps", color: "#2496ED" },
  { name: "Git", category: "Tools", color: "#F05032" },
  { name: "AI/LLM", category: "AI/ML", color: "#8B5CF6" },
  { name: "JavaScript", category: "Language", color: "#F7DF1E" },
  { name: "HTML5", category: "Frontend", color: "#E34F26" },
  { name: "CSS3", category: "Frontend", color: "#1572B6" },
  { name: "MySQL", category: "Database", color: "#4479A1" },
];

export const projects = [
  {
    id: "1",
    title: "Netflix Clone",
    description: "A streaming platform clone with user authentication, video playback, and responsive design mimicking Netflix's interface.",
    longDescription: "Full-featured Netflix clone with user authentication, browse functionality, video streaming capabilities, and responsive design. Implemented modern UI patterns and smooth animations for an engaging user experience.",
    image: "/projects/netflix.jpg",
    tags: ["React", "Next.js", "TypeScript", "Tailwind CSS", "MongoDB"],
    githubUrl: "https://github.com/sathish/netflix-clone",
    liveUrl: "https://netflix-clone-demo.com",
    featured: true,
  },
  {
    id: "2",
    title: "Spotstar",
    description: "A hybrid web application combining the best features of Spotify and Hotstar for music and video streaming.",
    longDescription: "Innovative web application that merges music streaming (Spotify-like) and video streaming (Hotstar-like) capabilities into one platform. Features include media playback, user playlists, content recommendations, and a modern responsive interface.",
    image: "/projects/spotstar.jpg",
    tags: ["HTML5", "CSS3", "JavaScript", "Bootstrap", "API Integration"],
    githubUrl: "https://github.com/sathish/spotstar",
    liveUrl: "https://spotstar-demo.com",
    featured: true,
  },
  {
    id: "3",
    title: "Spicy Kitchen - Restaurant Management",
    description: "Full-stack restaurant management system with online ordering, menu management, and admin dashboard.",
    longDescription: "Comprehensive restaurant management system developed as a college project. Features include online ordering system, dynamic menu management, order tracking, customer management, and admin dashboard. This project provided hands-on experience with full-stack web development, database design, and server-side programming.",
    image: "/projects/restaurant.jpg",
    tags: ["PHP", "MySQL", "HTML5", "CSS3", "Bootstrap", "JavaScript"],
    githubUrl: "https://github.com/sathish/spicy-kitchen",
    featured: true,
  },
  {
    id: "4",
    title: "Play School Website - Sunshine School",
    description: "Interactive website for Sunshine Play School with information about programs, activities, and enrollment.",
    longDescription: "Developed a vibrant and user-friendly website for Sunshine Play School. Features include program information, activity galleries, enrollment forms, and parent resources. Designed with colorful, child-friendly UI elements.",
    image: "/projects/playschool.jpg",
    tags: ["HTML5", "CSS3", "JavaScript", "Bootstrap"],
    githubUrl: "https://github.com/sathish/sunshine-playschool",
    liveUrl: "https://sunshine-playschool.com",
    featured: false,
  },
  {
    id: "5",
    title: "Personal Portfolio",
    description: "First personal portfolio website showcasing projects, skills, and experience with clean, modern design.",
    longDescription: "Created my first personal portfolio website to showcase projects and skills. Built with HTML5, CSS3, Bootstrap, and JavaScript, featuring responsive design, smooth animations, and an intuitive user interface.",
    image: "/projects/portfolio-old.jpg",
    tags: ["HTML5", "CSS3", "Bootstrap", "JavaScript"],
    githubUrl: "https://github.com/sathish/portfolio-v1",
    liveUrl: "https://sathish-portfolio-v1.com",
    featured: false,
  },
  {
    id: "6",
    title: "Digital Invitation Card",
    description: "Elegant and interactive digital invitation card with animations and responsive design.",
    longDescription: "Designed and developed a beautiful digital invitation card with smooth animations, interactive elements, and mobile-responsive layout. Perfect for sharing special occasions digitally.",
    image: "/projects/invitation.jpg",
    tags: ["HTML5", "CSS3", "JavaScript", "Animations"],
    githubUrl: "https://github.com/sathish/invitation-card",
    liveUrl: "https://invitation-demo.com",
    featured: false,
  },
];

export const experience = [
  {
    id: "1",
    title: "Software Engineer",
    company: "SkillRank",
    location: "Remote",
    period: "July 2024 - Present",
    description: "Full-stack development of innovative web applications. Building scalable solutions using modern technologies and best practices.",
    achievements: [
      "Developed and deployed multiple full-stack features using Next.js and AWS",
      "Implemented AI/LLM integrations for enhanced user experiences",
      "Optimized application performance and database queries",
      "Collaborated with cross-functional teams in agile environment",
    ],
  },
];

export const siteMetadata = {
  title: "Sathish Kumar - Software Engineer Portfolio",
  description: "Portfolio website of Sathish Kumar, a Software Engineer specializing in full-stack web development with React, Next.js, and TypeScript.",
  url: "https://sathish-portfolio.com",
  image: "/og-image.jpg",
  author: "Sathish Kumar",
  keywords: "software engineer, web developer, react, next.js, typescript, portfolio",
};
